# Default workspace configuration for Claude Code Morph
name: default
layout:
  # Top panel - Prompt Generator
  - type: PromptPanel
    id: prompt
    params: {}
      
  # Bottom panel - Claude Terminal
  - type: RobustTerminalPanel
    id: terminal
    params: {}

# Additional settings
settings:
  theme: dark
  auto_save: true
  hot_reload: true